language: node_js
node_js:
    - "7.10.0"
install:
    - npm install
script:
    - npm test
cache: 
  - npm install
before_script:
  - createdb more_recipes --username=postgres
  - sequelize db:migrate
after_success:
    - npm run coveralls